### PR TITLE
Fix printf and exit calls in fland1.c

### LINKED ISSUE #70: Fix fland1.c
> File 'hydromad/libs/i386/hydromad.dll':
>   Found 'exit', possibly from 'exit' (C), 'stop' (Fortran)
>     Object: 'fland1.o'
>   Found 'printf', possibly from 'printf' (C)
>     Object: 'fland1.o'
> File 'hydromad/libs/x64/hydromad.dll':
>   Found 'exit', possibly from 'exit' (C), 'stop' (Fortran)
>     Object: 'fland1.o'
>   Found 'printf', possibly from 'printf' (C)
>     Object: 'fland1.o'
> 
> Compiled code should not call entry points which might terminate R nor
> write to stdout/stderr instead of to the console, nor use Fortran I/O
> nor system RNGs.
> 
> See 'Writing portable packages' in the 'Writing R Extensions' manual.

### PR DESCRIPTION
**Pull request by mortisflux**
## Patch: issue 70 fix

R CMD check is currently returning this error:

```
 * checking compiled code ... WARNING
##[warning]File ‘hydromad/libs/hydromad.so’:
  Found ‘__printf_chk’, possibly from ‘printf’ (C)
    Object: ‘fland1.o’
  Found ‘exit’, possibly from ‘exit’ (C)
    Object: ‘fland1.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.
```

Calling `printf` and `exit` are not advised when writing C code. `Rprintf` should be used in place of `printf` (now changed). `exit` will terminate a user's R process, so this has been changed to `error` instead and now includes an  message - please let me know if you think this message could be improved!

Helpful resources:
[https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Printing](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Printing)
[https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Error-signaling](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Error-signaling)

### All Submissions:

* [x] Have you followed the guidelines in our **CONTRIBUTING** document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

Closes #70 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue. List the bug ID if applicable)

### CODE REVIEW

File: src/fland1.c [hunk 1]
```diff
@@ -1,24 +1,26 @@
...
+#include <R_ext/Print.h>
 #include <math.h>
 #include <stdio.h>
 #include <stdlib.h>
 
 #define EPS 1.e-5 /* Minimum parameter value */
 
 void fland1(struct SMA *sma, struct FSUM1 *fsum1) {
-
+
```
Comment (jnothman) [inline src/fland1.c:11]: the linter is complaining about this insertion of whitespace.

**Comment by josephguillaume** [comment]
It looks like the right fix. Thanks!
It would be good to make the sure tests run in R CMD check are still passing, specifically the ones calling sacramento.sim. At the moment there's a (perhaps unrelated) error.

File: src/fland1.c (hunk 1 above)
Comment (mortisflux) [reply src/fland1.c]: It is still complaining despite its removal

Comment (mortisflux) [reply src/fland1.c]: All good now :)

**Comment by mortisflux** [comment]
> It looks like the right fix. Thanks!
> It would be good to make the sure tests run in R CMD check are still passing, specifically the ones calling sacramento.sim. At the moment there's a (perhaps unrelated) error.

I don't think sure this patch is what's causing the fail in test-statistics.R to fail in R CMD check. R CMD check for this PR returned (on ubuntu with R 4.0):

```
> test_check("hydromad")
── 1. Failure: formula works within functions (@test-statistics.R#81)  ─────────
(time.formula[3] - time.fun[3])/time.fun[3] is not strictly less than 0.1. Difference: 0.0627
```

This test is also failing in the roxygen2_documentation_v2 branch, which still has the old version of the C code:
[https://github.com/josephguillaume/hydromad/runs/925826151?check_suite_focus=true](https://github.com/josephguillaume/hydromad/runs/925826151?check_suite_focus=true)

**Comment by josephguillaume** [comment]
I don't think so either, but it wasn't clear to me from R CMD check whether all the other tests have passed.
I'm happy to merge this if you can confirm that this test passes (i.e. the sacramento model runs successfully)
https://github.com/josephguillaume/hydromad/blob/master/tests/testthat/test-sma-sim.R#L123

**Comment by mortisflux** [comment]
> I don't think so either, but it wasn't clear to me from R CMD check whether all the other tests have passed.
> I'm happy to merge this if you can confirm that this test passes (i.e. the sacramento model runs successfully)
> https://github.com/josephguillaume/hydromad/blob/master/tests/testthat/test-sma-sim.R#L123

test-sma-sim.R#L123 appears to be fine when I run devtools::test() locally on this branch, and the majority of tests in test-sma-sim.R are also ok:

`✓ | 101   1   | Soil Moisture Accounting models [1.3 s]`

The exception is L136 ("scalar simulation runs") which returns:

```
test-sma-sim.R:139: warning: scalar simulation runs
all parameters are fixed, so can not fit
```

**Comment by josephguillaume** [comment]
Thanks!
