### PR TITLE
Fix stats:::tsdiag.Arima

### LINKED ISSUE #134: R CMD check warning: stats:::tsdiag.Arima
# Issue: warning arising from stats:::tsdiag.Arima

## Issue summary:
R CMD check is currently returning the following warning:

```
W  checking dependencies in R code (1.8s)
   Unexported object imported by a ':::' call: ‘stats:::tsdiag.Arima’
     See the note in ?`:::` about the use of this operator.
     Including base/recommended package(s):
     ‘stats’
```

`tsdiag.Arima` is an internal function from `stats` so it can't be called using `::`, however, R CMD check discourages the use of `:::` calls and returns a warning call.

## Possible Solutions
1. Ask the developers of `stats` to expose this function.
2. Bring `tsdiag.Arima` into hydromad as a private utility function.
3. Cast object as a `stats::arima` before applying `tsdiag`.

### PR DESCRIPTION
**Pull request by mortisflux**
## Patch for tsdiag.Arima

This PR is to address #134. R CMD check doesn't allow `:::` calls, so `tsdiag.Arima` is now being imported via `getS3method()`. The previous warning is now gone when `devtools::check` is run (locally at least).

### All Submissions:

* [x] Have you followed the guidelines in our **CONTRIBUTING** document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

Closes #134 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue. List the bug ID if applicable)

### CODE REVIEW

File: R/ltv.R [hunk 1]
```diff
@@ -369,5 +368,7 @@ vcov.ltv <- function(object, ...) {
 }
 
 tsdiag.ltv <- function(object, gof.lag = 10, ...) {
-  stats:::tsdiag.Arima(object, gof.lag, ...)
+  requireNamespace(stats, quietly = TRUE)
+  getS3method("tsdiag", "Arima")
+  tsdiag.Arima(object, gof.lag, ...)
 }
```
Comment (josephguillaume) [inline R/ltv.R:374]: There's several things I'm unsure about here that your testing might have addressed.
- I would have thought that `requireNamespace` is not needed for stats given that it is always loaded, at least on the search path
- As far as I understand, getS3method is a function, not a procedure, so it actually returns the function tsdiag.Arima, which then needs to be called, i.e. it would have to be `tsdiag.Arima <- getS3method("tsdiag","Arima")`

I'm happy to be corrected. This is a little tricky, hence why I've never bothered to resolve it.
I assume we don't have any tests for this function given it produces a plot. Do we have an example of it that could be used for testing?

Comment (jnothman) [reply R/ltv.R:374]: It might be worth adding a smoke test for this kind of thing.

Comment (mortisflux) [reply R/ltv.R:374]: @josephguillaume you're correct because running `getS3method("tsdiag", "Arima")` returns the function, so it seems I do need to assign it. And yup, there are no tests for it at present, can set up a smoke test.

Comment (mortisflux) [reply R/ltv.R:373]: I've updated this PR with the changes proposed above. Since `arima` only accepts a univariate time series as input, I've implemented the smoke test correctly by selecting a particular column from a dataset. @josephguillaume is this how you would use `tsdiag` with `arima`?

> I assume we don't have any tests for this function given it produces a plot. Do we have an example of it that could be used for testing?

The smoke test I've included makes sure that the function tsdiag() returns an object with the correct type of class, and that tsdiag returns an error when used on data that has more than one variable. I've also included a quick smoke test for xyplot here to demonstrate that xyplot doesn't work on arima models - this can be moved to a new PR (perhaps the upgraded test suite).

File: tests/testthat/test-smoke-tests.R [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+context("Smoke tests")
+
+data(Cotter)
+ts90s <- window(Cotter$Q, start = "1990-01-01", end = "1999-12-31")
+
+## Test that tsdiag.hydromad returns correct class
+test_that("can plot arima models with tsdiag", {
+  expect_type(tsdiag(arima(Cotter$P)), "NULL")
+  expect_type(tsdiag(arima(ts90s)), "NULL")
```
Comment (josephguillaume) [inline tests/testthat/test-smoke-tests.R:12]: I'm not sure if this is what we need after all - a NULL class isn't informative. Is it better just to say we expect there's no error?

File: tests/testthat/test-smoke-tests.R [hunk 3]
```diff
@@ -0,0 +1,21 @@
+library(testthat)
+library(hydromad)
+
+context("Smoke tests")
+
+data(Cotter)
+ts90s <- window(Cotter$Q, start = "1990-01-01", end = "1999-12-31")
+
+## Test that tsdiag.hydromad returns correct class
+test_that("can plot arima models with tsdiag", {
```
Comment (josephguillaume) [inline tests/testthat/test-smoke-tests.R:10]: These examples don't actually trigger tsdiag.hydromad - none of the first arguments are hydromad objects

Comment (josephguillaume) [reply tests/testthat/test-smoke-tests.R:10]: I think we need to check how these functions are actually used in the code
It seems there is no exported way of creating an ltv object and tsdiag.ltv is not exported either
```
U <- ts(rpois(200, lambda=0.25))
Q <- filter(0.5 * U, filter=0.5, method="recursive")
Q <- Q + rnorm(200, sd=0.1)
Q <- pmax(Q, 0)
foo <- hydromad:::ltv(Q, U, na=1, nb=1, nc=1)
hydromad:::tsdiag.ltv(foo)
```

The hydromad method relies on a $uh being added to the object and I haven't yet tracked down which function does that.

Comment (josephguillaume) [reply tests/testthat/test-smoke-tests.R:10]: Sorry to do this to you, but my thought is now to remove the testing code from this PR and add an issue. I'm satisfied that the changes above are correct.

File: tests/testthat/test-smoke-tests.R [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+  expect_type(tsdiag(arima(ts90s)), "NULL")
+  expect_error(tsdiag(Cotter))
+})
+
+## Test that xyplot.hydromad works returns correct class
+test_that("can plot data with xyplot plot", {
+  expect_type(xyplot(Cotter), "trellis")
+  expect_type(xyplot(ts90s), "trellis")
+  expect_error(xyplot(arima(ts90s)))
+})
```
Comment (josephguillaume) [inline tests/testthat/test-smoke-tests.R:21]: I'm fairly sure none of the S3 methods called here are defined within hydromad - this would be xyplot.zoo for the first two and xyplot.arima for the third.

File: tests/testthat/test-smoke-tests.R (hunk 2 above)
Comment (josephguillaume) [reply tests/testthat/test-smoke-tests.R:12]: Not that tsdiag.Arima, which is called here, is defined in stats not in hydromad

File: tests/testthat/test-smoke-tests.R (hunk 3 above)
Comment (mortisflux) [reply tests/testthat/test-smoke-tests.R:10]: I went to xyplot.hydromad.Rd to grab an example for testing:

```
data(Canning)
cannCal <- window(Canning, start = "1978-01-01", end = "1982-12-31")
mod <-
  hydromad(cannCal, sma = "cwi", tw = 162, f = 2, l = 300,
           t_ref = 0, scale = 0.000284,
           routing = "expuh", tau_s = 4.3, delay = 1, warmup = 200)
```

Unless I'm mistaken, `mod` should be a hydromad object? I tried a couple of things:

1. `hydromad::tsdiag(arima(mod))` returns `Error in arima(mod) : 'x' must be numeric` since `arima` only accepts a univariate time series. 

2. `hydromad::tsdiag(arima(mod$data$P))` returns a plot.

3. `hydromad::tsdiag(mod)` returns `Error in sqrt(object$sigma2) : non-numeric argument to mathematical function`.

I feel like I'm missing something here. Am I using an incorrect type of hydromad object to test this out, or is it incorrect to try and force a hydromad object to an arima model?

Comment (mortisflux) [reply tests/testthat/test-smoke-tests.R:10]: Ah I posted my comment before refreshing the pages, so I didn't see that you'd made a new comment.

Comment (mortisflux) [reply tests/testthat/test-smoke-tests.R]: No worries, I'll taken out the tests.

Comment (josephguillaume) [reply tests/testthat/test-smoke-tests.R]: Sorry - I've been commenting between other tasks and therefore a bit adhoc
`tsdiag(mod)` should work, but as you found out, it only works for some hydromad objects and I'm not sure which yet.

**Comment by josephguillaume** [comment]
Thanks! Sorry about the confusion on this one, and thanks for adding the new issue to follow up later.
