### PR TITLE
fix require and library in code to conform CRAN

### LINKED ISSUE #61: Deal with 'library' or 'require' calls in package code
CRAN policy does not permit 'library' or 'require' calls in package code.

We load 'ff' 'ggplot2' 'parallel' 'playwith'

Instructions in R CMD CHECK say:
> Please use :: or requireNamespace() instead.
> See section 'Suggested packages' in the 'Writing R Extensions' manual.

Need to select a policy for dealing with suggested packages in hydromad.

### PR DESCRIPTION
**Pull request by WillemVervoort**
### All Submissions:

* [X] Have you followed the guidelines in our **CONTRIBUTING** document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

Hope this works now

closes #61 
Closes #xxxxx

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue. List the bug ID if applicable)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing core functionality to change) 

### New Feature Submissions checklist:

1. [ ] Have you ensured there are no conflicts with major packages (e.g. tidyverse, MASS) or base R packages?
2. [ ] Does your new feature require documentation, and if so, have you updated the documentation?
3. [ ] Have you added tests for your features, and do your features pass all tests?
4. [ ] Have you linted your code with lintr locally prior to submission?
5. [ ] Have you styled your code with styler locally prior to submission?
6. [ ] Have you [benchmarked](https://www.alexejgossmann.com/benchmarking_r/) the performance of your code if applicable (e.g. with microbenchmark)?
7. [ ] Does your new feature comply with existing model APIs (e.g. for models, optimisation algorithms, objective functions)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you added tests for your core features and do your core features pass all tests?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Does your code run on all major platforms (Windows, macOS, Linux)?
* [ ] Have you demonstrated backwards compatibility and compatibility with the current development version, or discussed a potential break in backwards compatibility?
* [ ] Have you updated the package vignettes?

### CODE REVIEW

File: R/evalParsRollapply.R [hunk 1]
```diff
@@ -18,7 +18,7 @@ evalParsTS <- function(par.matrix, object,
   }
 
   # Sets default settings for parallelisation if missing
-  parallel <- hydromad.parallel(parallel)
+  parallel <- hydromad:::hydromad.parallel(parallel)
```
Comment (josephguillaume) [inline R/evalParsRollapply.R:21]:
```suggestion
  parallel <- hydromad.parallel(parallel)
```
::: was probably needed for your testing, but not within the package - R CMD CHECK will give a warning about this

File: R/evalParsRollapply.R [hunk 2]
```diff
@@ -34,8 +34,8 @@ evalParsTS <- function(par.matrix, object,
     }
   } else {
     ## Use disk
-    if (!require("parallel")) stop("package parallel is required for evalParsTS if filehash.name is not NULL and parallel$method is not 'foreach'")
-    if (!require("ff")) stop("package ff is required for evalParsTS if filehash.name is not NULL and parallel$method is not 'foreach'")
+    # if (!require("parallel")) stop("package parallel is required for evalParsTS if filehash.name is not NULL and parallel$method is not 'foreach'")
```
Comment (josephguillaume) [inline R/evalParsRollapply.R:37]: It looks like removing this will cause the parallel package to cause an error elsewhere?
Perhaps it's better to keep both of these as requireNamespace?

File: R/tellTS.R [hunk 3]
```diff
@@ -21,8 +21,8 @@ tellTS.default <- function(x, ts.matrix, fun,
   ))
   switch(parallel,
     "clusterApply" = {
-      clusterEvalQ(cl, library(sensitivity))
-      clusterEvalQ(cl, library(ff))
+      clusterEvalQ(cl, requireNamespace(sensitivity))
+      clusterEvalQ(cl, requireNamespace(ff))
       clusterExport(cl, c("ts.matrix", "x", "fun"), envir = environment())
```
Comment (josephguillaume) [inline R/tellTS.R:26]: This is a tricky one. These are actually commands to be run on a remote server, so we probably need some kind of additional error handling if requireNamespace is used instead of library.

**Comment by josephguillaume** [comment]
Thanks Willem. It looks like we gave you a tricky job here. There's still a few I'll have to look into.

@jnothman:
Some of these relate to meaningfulness of errors. Do you have any advice on how to approach this?
i.e. we were using require/requireNamespace to catch an error sooner and give a more meaningful error.

In the longer term, is it possible/worthwhile to have tests that blacklist certain forms of difficult to interpret error messages?

File: R/evalParsRollapply.R (hunk 2 above)
Comment (WillemVervoort) [reply R/evalParsRollapply.R:37]: It didn't look like that, it seemed like you call everything parallel:: anyway later in the script.
More importantly should consider to include parallel in the dependencies? You use it in a quite a few scripts and might also open opportunities for making SCE a Dream parallel

File: R/tellTS.R (hunk 3 above)
Comment (WillemVervoort) [reply R/tellTS.R:26]: Yes, I wasn't sure here. if you use foreach you can simply export the libraries within the call, is there a way we can rewrite the cluster calls as a foreach?
Otherwise we need to work out a different way to export the libraries to the nodes

File: R/evalParsRollapply.R (hunk 1 above)
Comment (WillemVervoort) [reply R/evalParsRollapply.R:21]: fair enough I can remove this

File: R/tellTS.R (hunk 3 above)
Comment (WillemVervoort) [reply R/tellTS.R:26]: Second thought, do we need to replace library() here? Maybe this would not create an error in R CMD check?

**Comment by jnothman** [comment]
> In the longer term, is it possible/worthwhile to have tests that blacklist certain forms of difficult to interpret error messages?

I am not sure I entirely understand... When we're talking about requireNamespace usage, I assume that the error message later is not *too* obscure because it should specify that it was unable to locate that library??

In other cases, I'd wonder how you would trigger the error messages to check that they are not "difficult". It reminds me of "fuzz testing" where you might send random queries or parameter combinations to a system, and making sure it responds without breaking the system. [`fuzzr`](https://cran.r-project.org/web/packages/fuzzr/vignettes/fuzzr.html) might do what you want, if you then want to testthat some random data does not produce unreasonable error messages...
However, this would be relatively costly in runtime (and engineering time?) compared to value. You could do it as an occasional test.

File: R/evalParsRollapply.R (hunk 1 above)
Comment (WillemVervoort) [reply R/evalParsRollapply.R]: removed in 2521115

File: R/evalParsRollapply.R (hunk 2 above)
Comment (WillemVervoort) [reply R/evalParsRollapply.R]: reinstated requireNamespace() in 4894467

File: R/paretoObjectivesVaryWeights.R [hunk 4]
```diff
@@ -2,9 +2,8 @@ paretoObjectivesVaryWeights <- function(MODEL, objective = hydromad.getOption("o
   objective <- buildCachedObjectiveFun(objective, MODEL)
   switch(hydromad.getOption("parallel")[["paretoObjectivesVaryWeights"]],
     "clusterApply" = {
-      if (!require("parallel")) stop('package parallel is required for paretoObjectivesVaryWeights if hydromad.getOption("parallel")[["paretoObjectivesVaryWeights"]]=="clusterApply"')
-      clusterExport(cl, c("objective", "fitBy", "MODEL"), envir = environment())
```
Comment (josephguillaume) [inline R/paretoObjectivesVaryWeights.R:6]: As discussed, let's make this a `requireNamespace` because I'm not sure whether I prefer the default error message or the custom one

File: R/tellTS.R (hunk 3 above)
Comment (josephguillaume) [reply R/tellTS.R:26]: As discussed, please do see what R CMD check says.
The right solution does seem to be to check the output of the clusterEvalQ call and throw an error if needed.

library(sensitivity) could be removed by using sensitivity::tell but library(ff) is needed in order for tell to be able to read the ts.matrix I believe, i.e. there's no explicit ff calls.

Feel free to just not fix this one and we can accept the rest of the changes.

File: R/paretoObjectivesVaryWeights.R (hunk 4 above)
Comment (WillemVervoort) [reply R/paretoObjectivesVaryWeights.R:6]: fixed in 60d1286

File: R/tellTS.R (hunk 3 above)
Comment (WillemVervoort) [reply R/tellTS.R:25]: Still to run R CMD CHK, fails at the moment on other issues, does not flag the "library" issue

**Comment by josephguillaume** [comment]
Thanks! Sorry about all the trouble along the way, and my indecisiveness!
